# Generated by Django 3.0.2 on 2020-02-01 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url_image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
                ('stock', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Stock')),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Rental price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Sale price')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('likes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Likes')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Rental date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Return date')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Cost')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_movie', to='movies_rental.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Rental date')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Cost')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_movie', to='movies_rental.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
